---
title: "Mamatoto: Instant HIE Implementation"
subtitle: "An instant HIE implementation for LMIC that showcases data sharing for maternal care within a brick and click model"
details: |
  Pharmaccess • Turn.io • IntelliSOFT Consulting
sidebar: false
toc: false
page-layout: full
format:
  html:
    template-partials:
      - html/home/title-block.html
program-logo: logo-pharmaccess.png #TODO: update to logo showing all partners
---


#### Instant OpenHIE

Instant OpenHIE aims to allow Health Information Exchange components to be packaged up, deployed, operated and scaled via a simple CLI.

##### Vision
The Instant OpenHIE project aims to reduce the costs and skills required for software developers to deploy applications conforming to an OpenHIE architecture. This will enable quicker initial solution testing, demonstrations. It will also serve as a starting point for faster production implementation and customisation.

Instant OpenHIE is a simple way for semi-technical persons to install and see a complex system working against a real-world use case. It will illustrate how interoperability can work to solve health challenges. It will also show how a national interoperability architecture could be created with open-source software and standards.

Instant OpenHIE aim to provide a simple, portable way to deploy health information exchange systems to facilitate:

1. Demonstrable reference products - those that align with the OpenHIE Community's vision for low resource contexts

2. Rapid software development of mediators and point-of-service systems by making it possible to launch several applications easily so the developer can focus on their task

3. Reproducible, version-controlled infrastructure for user-contributed tests of the OpenHIE Architecture profiles, workflows, and use cases.

4. Production-ready containers and orchestratable components that are deployable in any context.

5. Extensibility so that anyone may create Instant OpenHIE packages and plug them into the existing Instant OpenHIE functionality.
